### ISSUE TITLE
Generalize the Strategy Manager to all types of QoS

### ISSUE THREAD

**Issue by rdinizcal** [rdinizcal/sa-bsn#82]
In the current implementation of the engine package, there are methods of computing similar data (e.g., monitor_cost, monitor_reli). This makes it hard to read and maintain the class. Also, leads to accounts lot of duplication.

Generalizing the strategy manager with cost and reliability sub-classes is an internal requirement.

[IT.1] The developers would like to generalize the strategy manager node.

1. Extract Classes CostEngine and ReliEngine from Engine
2. Extract SuperClass from both

**Comment by ericbg27** [comment]
When trying to run with cost_engine in the strategy manager launch file, the following error appears:

NODES
  /
    cost_engine (adaptation_engine/cost_engine)

ROS_MASTER_URI=http://localhost:11311

process[cost_engine-1]: started with pid [10628]
/cost_engine
[monitoring]
[ERROR] [1614710974.857700332]: Received empty answer when asked for cost.
[ERROR] [1614710974.866871771]: Received empty answer when asked for event.
[analyze]
current system cost: 0
[FATAL] [1614710974.867479365]: ASSERTION FAILED
	file = /opt/ros/melodic/include/ros/publisher.h
	line = 102
	cond = false
	message = 
[FATAL] [1614710974.867691018]: Call to publish() on an invalid Publisher
[FATAL] [1614710974.867781487]: 

[cost_engine-1] process has died [pid 10628, exit code -5, cmd /home/eric/Documents/BSN/catkin_ws/devel/lib/adaptation_engine/cost_engine __name:=cost_engine __log:=/home/eric/.ros/log/02b1330a-7b88-11eb-a598-0800272416a6/cost_engine-1.log].
log file: /home/eric/.ros/log/02b1330a-7b88-11eb-a598-0800272416a6/cost_engine-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
